/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/chair.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials.FabricDenim003_3K}
        position={[0.04, 2.27, 0.04]}
        scale={[0.61, 0.12, 0.61]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials.WoodQuarteredChiffon001_6K}
        position={[0.04, 1.33, 0.04]}
        rotation={[0, 0.8, 0.25]}
        scale={[0.08, 0.79, 0.08]}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.FabricDenim003_3K}
        position={[0.04, 2.93, 0]}
        scale={0.87}
      />
    </group>
  );
}

useGLTF.preload("/chair.glb");
